name: Fetch Air Quality Hourly

on:
  schedule:
    # GitHub Actions는 UTC 기준. KST 05~20시는 UTC 20~23, 00~11시.
    - cron: '0 0-11 * * *'   # UTC 00~11 = KST 09~20
    - cron: '0 20-23 * * *'  # UTC 20~23 = KST 05~08 (이전날 UTC)
  workflow_dispatch: {}

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: |
          npm ci --ignore-scripts --no-audit --no-fund

      - name: Import from Excel
        run: |
          npm run import:air

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/data/air-quality.json
            git commit -m "chore(data): update air-quality.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi


