name: Fetch Air Quality Hourly

on:
  schedule:
    # GitHub Actions는 UTC 기준. KST 07~22시는 UTC 22~23, 00~13시.
    - cron: '0 0-11 * * *'   # UTC 00~11시 = KST 09~20시
    - cron: '0 22-23 * * *'  # UTC 22~23시 = KST 07~08시
    - cron: '0 17-19 * * *'  # 추가: UTC 17~19시 = KST 02~04시
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: |
          npm ci --ignore-scripts --no-audit --no-fund

      - name: Run fetch script
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
        run: |
          npm run fetch:air

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/data/air-quality.json
            git commit -m "chore(data): update air-quality.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi


